/* Generated by configure */
#ifndef config_h
#define config_h

#define HAVE_STDINT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UINT_LEAST32_T 1
#define HAVE_SYS_SELECT_H 1

#include "config2.h"

#endif
